

trigger:
- master

stages:
- stage: PublishArtifact
  displayName: Publish template files as artifact
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: PublishArtifact
      displayName: Copy and publish artifact
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
- stage: Dev
  displayName: 'Deploy to dev'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: Dev-Deploy-Group
      deployment: DeployInfrastructure
      displayName: 'Deploy ARM template'
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Azure Pass - Sponsorship(b22e16a2-5e73-42db-80b1-6f5350b9ad24)'
                  subscriptionId: 'b22e16a2-5e73-42db-80b1-6f5350b9ad24'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'Azure-Devops-RG'
                  location: 'East US'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Agent.BuildDirectory)/drop/template.json'
                  csmParametersFile: '$(Agent.BuildDirectory)/drop/parameters.json'
                  overrideParameters: '-environment $(Environment)'
                  deploymentMode: 'Incremental'
- stage: Test
  displayName: 'Deploy to test'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: QA-Deploy-Group
  jobs:
    - deployment: DeployInfrastructure
      displayName: 'Deploy ARM template'
      environment: QA
      strategy:
        runOnce:
          deploy:

             steps:
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Azure Pass - Sponsorship(b22e16a2-5e73-42db-80b1-6f5350b9ad24)'
                  subscriptionId: 'b22e16a2-5e73-42db-80b1-6f5350b9ad24'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'Azure-Devops-RG'
                  location: 'East US'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Agent.BuildDirectory)/drop/template.json'
                  csmParametersFile: '$(Agent.BuildDirectory)/drop/parameters.json'
                  overrideParameters: '-environment $(Environment)'
                  deploymentMode: 'Incremental'